import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.168.0/build/three.module.js';

const $ = (s) => document.querySelector(s);
const clamp = THREE.MathUtils.clamp;
const angleDelta = (a, b) => Math.atan2(Math.sin(b - a), Math.cos(b - a));

const CONFIG = {
  arena: 110, sightRange: 92, sightFov: Math.PI * .82, memorySize: 12,
  matchSeconds: 120, decisionHz: 4,
};

const scene = new THREE.Scene();
scene.background = new THREE.Color(0x708184);
scene.fog = new THREE.FogExp2(0x637275, .018);
const camera = new THREE.PerspectiveCamera(52, innerWidth / innerHeight, .1, 220);
const renderer = new THREE.WebGLRenderer({ canvas: $('#viewport'), antialias: true });
renderer.setPixelRatio(Math.min(devicePixelRatio, 1.6));
renderer.setSize(innerWidth, innerHeight);
renderer.shadowMap.enabled = true;
renderer.shadowMap.type = THREE.PCFSoftShadowMap;
renderer.toneMapping = THREE.ACESFilmicToneMapping;
renderer.toneMappingExposure = 1.05;

scene.add(new THREE.HemisphereLight(0xc9e8eb, 0x26322d, 2.1));
const sun = new THREE.DirectionalLight(0xffe7c2, 3.2);
sun.position.set(-24, 36, 16); sun.castShadow = true;
sun.shadow.mapSize.set(2048, 2048); sun.shadow.camera.left = sun.shadow.camera.bottom = -55;
sun.shadow.camera.right = sun.shadow.camera.top = 55; scene.add(sun);

const floor = new THREE.Mesh(new THREE.PlaneGeometry(180, 180), new THREE.MeshStandardMaterial({ color: 0x273538, roughness: .97, metalness: .08 }));
floor.rotation.x = -Math.PI / 2; floor.receiveShadow = true; scene.add(floor);
const grid = new THREE.GridHelper(144, 36, 0x53767a, 0x35494c); grid.position.y = .012; grid.material.opacity = .22; grid.material.transparent = true; scene.add(grid);

function box(w,h,d,color,metal=.7,rough=.46){
  const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color,metalness:metal,roughness:rough}));m.castShadow=true;m.receiveShadow=true;return m;
}
function cyl(r,l,color){const m=new THREE.Mesh(new THREE.CylinderGeometry(r,r,l,10),new THREE.MeshStandardMaterial({color,metalness:.85,roughness:.32}));m.castShadow=true;return m}
function poly(rTop,rBottom,h,color,sides=6){const m=new THREE.Mesh(new THREE.CylinderGeometry(rTop,rBottom,h,sides),new THREE.MeshStandardMaterial({color,metalness:.72,roughness:.42,flatShading:true}));m.castShadow=true;m.receiveShadow=true;return m}

// Ruined industrial arena with readable lanes and cover.
const obstacles=[];
function cover(x,z,w,h,d,rot=0){const g=new THREE.Group();const base=box(w,h,d,h>5?0x263336:0x344245,.25,.9);base.position.y=h/2;g.add(base);for(let i=0;i<Math.min(5,Math.ceil(h));i++){const stripe=box(w+.03,.12,d+.03,0xc27a31,.4,.65);stripe.position.y=.5+i*1.25;g.add(stripe)}if(h>5){const cap=box(w+.25,.25,d+.25,0x182326,.5,.72);cap.position.y=h+.12;g.add(cap)}g.position.set(x,0,z);g.rotation.y=rot;scene.add(g);obstacles.push({x,z,w,h,d,rot});}
cover(0,0,18,9,3);cover(-24,-12,3.2,9,14,.25);cover(25,13,3.2,10,15,-.3);cover(-12,27,13,2.4,2.6,.45);cover(15,-29,14,8,2.8,-.35);cover(-38,29,8,7,5,.15);cover(39,-28,8,8,5,-.2);cover(-37,-31,3,11,15,-.45);cover(38,32,3,10,14,.4);cover(2,43,18,7,2.8,.12);cover(-3,-45,18,8,2.8,-.12);
// Inner maze: staggered tall walls create occluded lanes instead of one open bowl.
cover(-22,9,3,8,18,.08);cover(22,-10,3,9,19,-.08);cover(-37,20,14,7,3,.12);cover(37,-20,14,8,3,-.12);cover(-18,-34,3,9,14,.35);cover(18,34,3,8,14,-.35);cover(-3,22,10,2.4,2.5,.05);cover(4,-22,10,2.3,2.5,-.05);
for(let i=0;i<22;i++){const h=5+Math.random()*12,w=3+Math.random()*6;const a=i/22*Math.PI*2,r=62+Math.random()*16;const b=box(w,h,w*.8,0x253235,.15,.92);b.position.set(Math.cos(a)*r,h/2,Math.sin(a)*r);b.rotation.y=Math.random();scene.add(b)}

function createMech({name,color,accent,loadout,position,heading}){
  const root=new THREE.Group();root.position.copy(position);root.rotation.y=heading;
  const legs=new THREE.Group(),legRigs=[];root.add(legs);
  for(const side of [-1,1]){const leg=new THREE.Group();leg.position.set(side*1.08,4.05,0);const upperArmor=poly(.68,.52,1.05,color,6);upperArmor.position.y=-.48;upperArmor.rotation.z=side*.08;leg.add(upperArmor);const thigh=poly(.52,.66,1.85,color);thigh.position.y=-1.42;thigh.rotation.z=side*.06;leg.add(thigh);const piston=cyl(.14,1.5,0x9aa9a8);piston.position.set(-side*.38,-1.1,-.18);piston.rotation.z=side*.12;leg.add(piston);const knee=cyl(.58,.42,0x171d1f);knee.rotation.z=Math.PI/2;knee.position.y=-2.42;leg.add(knee);const kneeCap=poly(.36,.5,.22,accent,8);kneeCap.rotation.z=Math.PI/2;kneeCap.position.set(side*.25,-2.42,0);leg.add(kneeCap);const shin=poly(.44,.62,1.65,color);shin.position.set(0,-3.32,.08);leg.add(shin);const ankle=cyl(.3,.5,0x151c1d);ankle.position.y=-4.12;leg.add(ankle);const foot=box(1.18,.38,1.8,0x222a2c);foot.position.set(0,-4.24,.35);foot.rotation.x=-.05;leg.add(foot);legs.add(leg);legRigs.push(leg);const hipJoint=new THREE.Mesh(new THREE.DodecahedronGeometry(.72,0),new THREE.MeshStandardMaterial({color:0x172023,metalness:.86,roughness:.3,flatShading:true}));hipJoint.position.set(side*1.08,4.05,0);hipJoint.castShadow=true;legs.add(hipJoint);const hipRing=cyl(.78,.3,accent);hipRing.rotation.z=Math.PI/2;hipRing.position.set(side*1.08,4.05,0);legs.add(hipRing)}
  const hip=poly(1.38,1.62,.78,0x222a2c,8);hip.rotation.z=Math.PI/2;hip.scale.z=.58;hip.position.y=4.05;legs.add(hip);
  const torso=new THREE.Group();torso.position.y=4.45;root.add(torso);
  const waist=cyl(.72,.48,0x151c1e);waist.position.y=.15;torso.add(waist);
  const core=new THREE.Mesh(new THREE.DodecahedronGeometry(1.65,0),new THREE.MeshStandardMaterial({color,metalness:.78,roughness:.38,flatShading:true}));core.scale.set(1.35,.82,1);core.position.y=1.25;core.castShadow=true;torso.add(core);
  const chest=poly(1.15,1.65,.72,accent,6);chest.rotation.z=Math.PI/2;chest.scale.z=.7;chest.position.set(0,1.45,.75);torso.add(chest);
  const cockpit=poly(.62,.84,.72,0x101819,6);cockpit.rotation.x=Math.PI/2;cockpit.position.set(0,1.62,1.38);torso.add(cockpit);
  const eye=cyl(.3,.08,accent);eye.rotation.x=Math.PI/2;eye.position.set(0,1.63,1.79);eye.material.emissive=new THREE.Color(accent);eye.material.emissiveIntensity=5;torso.add(eye);
  for(const side of [-1,1]){const shoulder=poly(.68,.9,1.05,color,6);shoulder.rotation.z=Math.PI/2;shoulder.position.set(side*1.72,1.38,.05);torso.add(shoulder);const vent=cyl(.3,.12,0x11191a);vent.rotation.z=Math.PI/2;vent.position.set(side*2.25,1.38,.05);torso.add(vent)}
  const reactor=cyl(.72,.7,0x1a2426);reactor.rotation.x=Math.PI/2;reactor.position.set(0,1.2,-1.45);torso.add(reactor);const reactorGlow=cyl(.42,.72,accent);reactorGlow.rotation.x=Math.PI/2;reactorGlow.position.set(0,1.2,-1.5);reactorGlow.material.emissive=new THREE.Color(accent);reactorGlow.material.emissiveIntensity=1.8;torso.add(reactorGlow);
  const antenna=box(.08,1.25,.08,0x2e3b3d);antenna.position.set(.75,2.55,.25);antenna.rotation.z=-.18;torso.add(antenna);const antennaTip=cyl(.11,.2,accent);antennaTip.position.set(.86,3.15,.25);antennaTip.material.emissive=new THREE.Color(accent);torso.add(antennaTip);
  const exhausts=[];for(const side of [-1,1]){const pipe=cyl(.18,1.5,0x171d1f);pipe.position.set(side*.78,2.25,-1.18);pipe.rotation.z=side*.08;torso.add(pipe);const tip=new THREE.Object3D();tip.position.set(side*.84,3.02,-1.18);torso.add(tip);exhausts.push(tip)}
  const weapons=[];
  loadout.forEach((weapon,i)=>{const side=i?1:-1;const mount=new THREE.Group();mount.position.set(side*2.55,1.5,.22);mount.userData.baseZ=.22;const housing=poly(.58,.72,1.45,color,6);housing.rotation.x=Math.PI/2;mount.add(housing);if(weapon.kind==='cannon'){const sleeve=cyl(.3,.72,0x303a3c);sleeve.rotation.x=Math.PI/2;sleeve.position.set(0,.1,1.05);mount.add(sleeve);const barrel=cyl(.14,2.65,0x12191a);barrel.rotation.x=Math.PI/2;barrel.position.set(0,.1,2.55);mount.add(barrel)}else{for(let x=-1;x<=1;x++)for(let y=0;y<2;y++){const tube=cyl(.14,1.2,0x20282a);tube.rotation.x=Math.PI/2;tube.position.set(x*.3,(y-.5)*.32,1);mount.add(tube)}}torso.add(mount);weapons.push(mount)});
  scene.add(root);
  return {name,root,legs,legRigs,torso,weapons,exhausts,loadout,health:100,heat:0,velocity:new THREE.Vector3(),heading,torsoYaw:0,ammo:loadout.map(w=>w.ammo),cooldown:[0,0],alive:true,lastAction:'IDLE',memory:[],seen:null,step:0,smokeTimer:0};
}

const player=createMech({name:'ATLAS // 01',color:0x2d5962,accent:0x42dcf3,position:new THREE.Vector3(-46,0,44),heading:2.1,loadout:[{name:'AC-12 AUTOCANNON',kind:'cannon',damage:6,rate:.18,ammo:Infinity},{name:'VLR-4 MISSILES',kind:'missile',damage:22,rate:2.4,ammo:8}]});
const enemy=createMech({name:'WRAITH // 02',color:0x67362f,accent:0xff543d,position:new THREE.Vector3(46,0,-44),heading:-1.0,loadout:[{name:'PULSE LANCE',kind:'cannon',damage:4,rate:.12,ammo:Infinity},{name:'SIEGE ROCKET',kind:'missile',damage:28,rate:3.4,ammo:5}]});
const blue2=createMech({name:'BASTION // 03',color:0x324b67,accent:0x64a9ff,position:new THREE.Vector3(-36,0,45),heading:2.0,loadout:[{name:'HEAVY CANNON',kind:'cannon',damage:9,rate:.38,ammo:Infinity},{name:'HAMMER MISSILES',kind:'missile',damage:25,rate:3,ammo:6}]});
const blue3=createMech({name:'LANCER // 05',color:0x285e59,accent:0x58f0cb,position:new THREE.Vector3(-24,0,31),heading:2.25,loadout:[{name:'PULSE ARRAY',kind:'cannon',damage:4,rate:.11,ammo:Infinity},{name:'HUNTER ROCKETS',kind:'missile',damage:18,rate:2.1,ammo:10}]});
const red2=createMech({name:'REAVER // 04',color:0x6b342f,accent:0xff784f,position:new THREE.Vector3(36,0,-45),heading:-1.1,loadout:[{name:'ROTARY GUN',kind:'cannon',damage:3,rate:.09,ammo:Infinity},{name:'BREACH MISSILES',kind:'missile',damage:24,rate:2.8,ammo:6}]});
const red3=createMech({name:'ONYX // 06',color:0x58374f,accent:0xff5ea8,position:new THREE.Vector3(24,0,-34),heading:-.9,loadout:[{name:'RAIL BURST',kind:'cannon',damage:8,rate:.32,ammo:Infinity},{name:'SWARM POD',kind:'missile',damage:16,rate:1.9,ammo:12}]});
const blueElite=createMech({name:'TITAN // B7 [ELITE]',color:0x243f58,accent:0x8beaff,position:new THREE.Vector3(-46,0,34),heading:2.05,loadout:[{name:'GAUSS BREAKER',kind:'cannon',damage:14,rate:.48,ammo:Infinity},{name:'APOCALYPSE POD',kind:'missile',damage:36,rate:3.8,ammo:8}]});
const redElite=createMech({name:'JUGGERNAUT // R8 [ELITE]',color:0x572b25,accent:0xff9b62,position:new THREE.Vector3(46,0,-34),heading:-1.05,loadout:[{name:'SIEGE DRIVER',kind:'cannon',damage:13,rate:.44,ammo:Infinity},{name:'ANNIHILATOR POD',kind:'missile',damage:38,rate:4,ammo:8}]});
for(const elite of [blueElite,redElite]){elite.health=180;elite.maxHealth=180;elite.root.scale.setScalar(1.16);elite.elite=true}
const blueTeam=[player,blue2,blueElite],redTeam=[enemy,red2,redElite],allMechs=[player,blue2,blue3,blueElite,enemy,red2,red3,redElite];
blueTeam.forEach(m=>m.team='BLUE');redTeam.forEach(m=>m.team='RED');[blue2,blue3,blueElite,red2,red3,redElite].forEach(m=>m.root.visible=false);
let activeBlue=[player],activeRed=[enemy];
let cameraMech=player;
const targetObstacle=new THREE.Group();targetObstacle.visible=false;const targetBase=box(5.4,2.8,3.2,0x514438,.35,.78);targetBase.position.y=1.4;targetObstacle.add(targetBase);const targetArmor=box(4.2,1.1,3.7,0x76513a,.55,.6);targetArmor.position.y=3.1;targetObstacle.add(targetArmor);const targetCore=box(1.1,.7,3.9,0xff5b45,.25,.35);targetCore.position.y=3.15;targetCore.material.emissive=new THREE.Color(0xff321d);targetCore.material.emissiveIntensity=1.5;targetObstacle.add(targetCore);enemy.root.add(targetObstacle);

const keys={};addEventListener('keydown',e=>{keys[e.code]=true;if(['Space','KeyR'].includes(e.code))e.preventDefault()});addEventListener('keyup',e=>keys[e.code]=false);
let running=false,timeLeft=CONFIG.matchSeconds,strategy='balanced',directive=$('#directive').value,decisionTimer=0,elapsed=0,shake=0,gameMode='training';
const projectiles=[];
const smoke=[];const smokeGeometry=new THREE.SphereGeometry(.32,7,6);
function emitSmoke(me,dt){if(!me.alive)return;me.smokeTimer-=dt;if(me.smokeTimer>0)return;me.smokeTimer=.12+Math.random()*.09;for(const exhaust of me.exhausts){const p=new THREE.Vector3();exhaust.getWorldPosition(p);const material=new THREE.MeshBasicMaterial({color:0x536064,transparent:true,opacity:.24,depthWrite:false});const puff=new THREE.Mesh(smokeGeometry,material);puff.position.copy(p);puff.scale.setScalar(.65+Math.random()*.45);scene.add(puff);smoke.push({mesh:puff,life:2.4,velocity:new THREE.Vector3((Math.random()-.5)*.32,.75+Math.random()*.35,(Math.random()-.5)*.32)})}}
function updateSmoke(dt){for(let i=smoke.length-1;i>=0;i--){const p=smoke[i];p.life-=dt;p.mesh.position.addScaledVector(p.velocity,dt);p.mesh.position.x+=Math.sin(elapsed*1.7+i)*dt*.08;p.mesh.scale.multiplyScalar(1+dt*.38);p.mesh.material.opacity=Math.max(0,.22*(p.life/2.4));if(p.life<=0){scene.remove(p.mesh);p.mesh.material.dispose();smoke.splice(i,1)}}}

function localPoint(x,z,o){const dx=x-o.x,dz=z-o.z,c=Math.cos(o.rot),s=Math.sin(o.rot);return{x:c*dx-s*dz,z:s*dx+c*dz}}
function hitsObstacle(x,z,r=0){if(x-r<=-CONFIG.arena/2||x+r>=CONFIG.arena/2||z-r<=-CONFIG.arena/2||z+r>=CONFIG.arena/2)return true;return obstacles.some(o=>{const p=localPoint(x,z,o);return Math.abs(p.x)<o.w/2+r&&Math.abs(p.z)<o.d/2+r})}
function mechRadius(me){return me.elite?2.55:2.05}
function mechCollisionAt(me,x,z,padding=0){let hit=null,best=Infinity;for(const other of allMechs){if(other===me||!other.root.visible)continue;const distance=Math.hypot(x-other.root.position.x,z-other.root.position.z),limit=mechRadius(me)+mechRadius(other)+padding;if(distance<limit&&distance<best){hit=other;best=distance}}return hit?{other:hit,distance:best,limit:mechRadius(me)+mechRadius(hit)+padding}:null}
function segmentHitsObstacle(a,b,o,pad=0){const p=localPoint(a.x,a.z,o),q=localPoint(b.x,b.z,o),dx=q.x-p.x,dz=q.z-p.z;let lo=0,hi=1;for(const [start,delta,min,max] of [[p.x,dx,-o.w/2-pad,o.w/2+pad],[p.z,dz,-o.d/2-pad,o.d/2+pad]]){if(Math.abs(delta)<1e-6){if(start<min||start>max)return false}else{let t1=(min-start)/delta,t2=(max-start)/delta;if(t1>t2)[t1,t2]=[t2,t1];lo=Math.max(lo,t1);hi=Math.min(hi,t2);if(lo>hi)return false}}return true}
function lineBlocked(a,b){return obstacles.some(o=>o.h>=5&&segmentHitsObstacle(a,b,o,.08))}
function clearanceAtAngle(me,offset,max=10){const angle=me.heading+offset,radius=mechRadius(me);for(let d=.4;d<=max;d+=.4){const x=me.root.position.x+Math.sin(angle)*d,z=me.root.position.z+Math.cos(angle)*d;if(hitsObstacle(x,z,radius)||mechCollisionAt(me,x,z,.15))return +(d-.4).toFixed(1)}return max}
function mobilityScan(me){return{front:clearanceAtAngle(me,0),frontLeft:clearanceAtAngle(me,-Math.PI/4),left:clearanceAtAngle(me,-Math.PI/2),frontRight:clearanceAtAngle(me,Math.PI/4),right:clearanceAtAngle(me,Math.PI/2),rear:clearanceAtAngle(me,Math.PI)}}
function enforceNavigation(me,nav){const scan=mobilityScan(me),nearby=allMechs.filter(other=>other!==me&&other.alive&&other.root.visible).map(other=>({other,distance:me.root.position.distanceTo(other.root.position),limit:mechRadius(me)+mechRadius(other)})).filter(x=>x.distance<x.limit+2).sort((a,b)=>a.distance-b.distance)[0];if(nearby){const bearing=Math.atan2(nearby.other.root.position.x-me.root.position.x,nearby.other.root.position.z-me.root.position.z),side=angleDelta(me.heading,bearing),turn=side>=0?-1:1;return{forward:nearby.distance<nearby.limit+.35?-.5:0,turn,safetyOverride:`UNIT_SEPARATION ${nearby.other.name} distance=${nearby.distance.toFixed(1)}m limit=${nearby.limit.toFixed(1)}m`,scan}}if(me.avoidanceUntil>elapsed){let error=angleDelta(me.heading,me.avoidanceHeading);if(Math.abs(error)>.18)return{forward:0,turn:Math.sign(error),safetyOverride:`DETOUR_ALIGN ${THREE.MathUtils.radToDeg(error).toFixed(1)}deg`,scan};if(scan.front<1.6){const side=scan.frontLeft+scan.left>=scan.frontRight+scan.right?-1:1;me.avoidanceHeading=me.heading+side*Math.PI/2;me.avoidanceUntil=elapsed+3.5;error=angleDelta(me.heading,me.avoidanceHeading);return{forward:0,turn:Math.sign(error),safetyOverride:'DETOUR_REPLAN',scan}}return{forward:.8,turn:0,safetyOverride:`DETOUR_ADVANCE ${(me.avoidanceUntil-elapsed).toFixed(1)}s`,scan}}const wallDanger=scan.front<1.6||(nav.forward>0&&(scan.front<3.2||(me.blockedLatch||0)>0));if(wallDanger){const side=scan.frontLeft+scan.left>=scan.frontRight+scan.right?-1:1;me.avoidanceHeading=me.heading+side*Math.PI/2;me.avoidanceUntil=elapsed+3.5;return{forward:0,turn:side,safetyOverride:`DETOUR_START front=${scan.front}m ${side<0?'LEFT':'RIGHT'}`,scan}}if(me.navTarget){const dx=me.navTarget.x-me.root.position.x,dz=me.navTarget.z-me.root.position.z,distance=Math.hypot(dx,dz),bearing=Math.atan2(dx,dz),error=angleDelta(me.heading,bearing);if(distance<9){const result={forward:scan.rear>2?-1:0,turn:0,safetyOverride:`TOO_CLOSE distance=${distance.toFixed(1)}m; forced ${scan.rear>2?'BACKWARD':'HOLD'}`,scan};me.lastSafetyOverride=result.safetyOverride;return result}if(Math.abs(error)>.44){const turn=Math.sign(error);const result={forward:0,turn,safetyOverride:`TARGET_NOT_AHEAD angle=${THREE.MathUtils.radToDeg(error).toFixed(1)}deg; forced ${turn<0?'TURN_LEFT':'TURN_RIGHT'}`,scan};me.lastSafetyOverride=result.safetyOverride;return result}if(distance<11&&nav.forward>0)return{forward:0,turn:0,safetyOverride:`ENGAGEMENT_RANGE distance=${distance.toFixed(1)}m; forced HOLD`,scan};if(nav.forward>0)return{forward:nav.forward,turn:Math.abs(error)>.12?Math.sign(error)*.28:0,safetyOverride:Math.abs(error)>.12?'COURSE_CORRECTION':null,scan}}return{...nav,safetyOverride:null}}
function canSee(observer,target){const d=observer.root.position.distanceTo(target.root.position);const aim=observer.heading+observer.torsoYaw;const targetAngle=Math.atan2(target.root.position.x-observer.root.position.x,target.root.position.z-observer.root.position.z);return d<CONFIG.sightRange&&Math.abs(angleDelta(aim,targetAngle))<CONFIG.sightFov/2&&!lineBlocked(observer.root.position,target.root.position)}
function snapshot(me,target){const visible=canSee(me,target),contactEvent=visible&&!me.hadVisual?'CONTACT_ACQUIRED':!visible&&me.hadVisual?'CONTACT_LOST':null;me.hadVisual=visible;if(visible)me.navTarget={x:target.root.position.x,z:target.root.position.z,seenAt:elapsed};const obstacleAnglesDeg=obstacles.map((o,id)=>{const corners=[[-o.w/2,-o.d/2],[o.w/2,-o.d/2],[o.w/2,o.d/2],[-o.w/2,o.d/2]].map(([x,z])=>{const c=Math.cos(o.rot),s=Math.sin(o.rot),wx=o.x+c*x+s*z,wz=o.z-s*x+c*z;return THREE.MathUtils.radToDeg(angleDelta(me.heading,Math.atan2(wx-me.root.position.x,wz-me.root.position.z)))});const dx=o.x-me.root.position.x,dz=o.z-me.root.position.z,distance=Math.hypot(dx,dz),center=THREE.MathUtils.radToDeg(angleDelta(me.heading,Math.atan2(dx,dz))),p=localPoint(me.root.position.x,me.root.position.z,o),edge=Math.hypot(Math.max(Math.abs(p.x)-o.w/2,0),Math.max(Math.abs(p.z)-o.d/2,0));return{id,centerAngleDeg:+center.toFixed(1),cornerAnglesDeg:corners.map(v=>+v.toFixed(1)),distance:+distance.toFixed(1),distanceToEdge:+edge.toFixed(1)}}).filter(o=>o.distance<32).sort((a,b)=>a.distanceToEdge-b.distanceToEdge).slice(0,8);return{at:+elapsed.toFixed(1),broadcast:contactEvent?{event:contactEvent,targetId:target.name,at:+elapsed.toFixed(1)}:null,self:{health:+me.health.toFixed(0),heat:+me.heat.toFixed(0),blocked:(me.blockedLatch||0)>0,blockedByUnit:me.blockedByUnit||null,hitboxRadius:mechRadius(me),mobility:mobilityScan(me),position:{x:+me.root.position.x.toFixed(1),z:+me.root.position.z.toFixed(1)},heading:+me.heading.toFixed(2),torsoYaw:+me.torsoYaw.toFixed(2),ammo:me.ammo},teamContact:me.teamContact||null,obstacleAnglesDeg,visibleEnemy:visible?{id:target.name,health:+target.health.toFixed(0),distance:+me.root.position.distanceTo(target.root.position).toFixed(1),bearing:+Math.atan2(target.root.position.x-me.root.position.x,target.root.position.z-me.root.position.z).toFixed(2),action:target.lastAction,position:{x:+target.root.position.x.toFixed(1),z:+target.root.position.z.toFixed(1)}}:null,memory:me.memory.slice(-CONFIG.memorySize),strategy,directive}}

// Four independent, narrow decision channels. This contract is suitable for parallel TypeSafe calls.
function decide(s){
  const seen=s.visibleEnemy,last=s.memory.filter(m=>m.enemy).at(-1)?.enemy;
  const target=seen?.position||last?.position||{x:0,z:0};const dx=target.x-s.self.position.x,dz=target.z-s.self.position.z,dist=Math.hypot(dx,dz);const desired=Math.atan2(dx,dz);
  const ideal=strategy==='aggressive'?12:strategy==='defensive'?30:21;
  const turretError=angleDelta(s.self.heading+s.self.torsoYaw,desired);
  const chassisError=angleDelta(s.self.heading,desired);
  return {navigation:{forward:s.self.blocked?0:dist>ideal+3?1:dist<ideal-3?-.65:0,turn:s.self.blocked?(Math.sin(elapsed)>0?1:-1):Math.abs(chassisError)>.3?Math.sign(chassisError):0},torso:{turn:seen?(Math.abs(turretError)<.08?0:Math.sign(turretError)):.65},targeting:{track:seen?'visual':last?'memory':'search',targetId:seen?.id||null},weapon:{primary:!!seen&&dist<45&&s.self.heat<86,secondary:!!seen&&dist>16&&dist<48&&s.self.ammo[1]>0&&s.visibleEnemy.health<75}};
}
function commandFromJev(result,s){
  const seen=s.visibleEnemy,last=s.memory.filter(m=>m.enemy).at(-1)?.enemy,nav=result.navigation;
  return {navigation:{forward:nav==='forward'?1:nav==='backward'?-1:0,turn:nav==='turn_left'?-1:nav==='turn_right'?1:0},torso:{turn:result.turret==='turn_left'?-1:result.turret==='turn_right'?1:0},targeting:{track:seen?'visual':last?'memory':'search',targetId:seen?.id||null},weapon:{primary:result.weapon==='autocannon'&&!!seen,secondary:result.weapon==='missiles'&&!!seen}};
}
async function requestJev(me,target){
  if(me.decisionPending||!me.alive)return;me.decisionPending=true;const s=snapshot(me,target);
  if(s.broadcast?.event==='CONTACT_ACQUIRED')logBroadcast(s.broadcast);
  try{const response=await fetch('/api/decide',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:gameMode,snapshot:s})});const result=await response.json();if(!response.ok)throw new Error(result.error||'JEV error');me.command=commandFromJev(result,s);me.aiModel=result.model;$('#ai-status').textContent=`${result.model} · ${result.usage.output_tokens} TOK`;$('#ai-status').style.color='var(--blue)';logDecision(me.command,s);fetch('/api/telemetry',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({unit:me.name,mode:gameMode,snapshot:s,jev:result,requestedCommand:me.command,runtimeSafety:me.lastSafetyOverride||null})}).catch(()=>{})}catch(error){me.command=decide(s);$('#ai-status').textContent='LOCAL FALLBACK';$('#ai-status').style.color='var(--orange)';console.warn(error)}finally{remember(me,s);me.decisionPending=false}}
function remember(me,s){me.memory.push({at:s.at,enemy:s.visibleEnemy?{position:s.visibleEnemy.position,health:s.visibleEnemy.health,action:s.visibleEnemy.action}:null,selfHealth:s.self.health});if(me.memory.length>CONFIG.memorySize)me.memory.shift()}
function applyBot(me,target,cmd,dt){const nav=enforceNavigation(me,cmd.navigation),chassisDelta=nav.turn*dt*.82;me.turnRate=nav.turn;me.heading+=chassisDelta;me.torsoYaw-=chassisDelta;const bearing=Math.atan2(target.root.position.x-me.root.position.x,target.root.position.z-me.root.position.z),visible=canSee(me,target),turretError=angleDelta(me.heading+me.torsoYaw,bearing);let turretTurn=cmd.torso.turn;if(visible)turretTurn=Math.abs(turretError)<.045?0:Math.sign(turretError);me.torsoYaw+=turretTurn*dt*Math.min(1.15,Math.max(.24,Math.abs(turretError)*2.2));me.torsoYaw=clamp(me.torsoYaw,-THREE.MathUtils.degToRad(100),THREE.MathUtils.degToRad(100));const f=new THREE.Vector3(Math.sin(me.heading),0,Math.cos(me.heading));me.velocity.copy(f.multiplyScalar(nav.forward*6));moveMech(me,dt);const finalError=angleDelta(me.heading+me.torsoYaw,bearing),aimed=canSee(me,target)&&Math.abs(finalError)<.09;if(cmd.weapon.primary&&aimed)fire(me,target,0);if(cmd.weapon.secondary&&aimed)fire(me,target,1);me.lastAction=cmd.weapon.secondary&&aimed?'MISSILE':cmd.weapon.primary&&aimed?'FIRING':me.velocity.length()>.1?'MOVING':nav.turn?'TURNING':turretTurn?'SCANNING':'HOLDING'}
function moveMech(me,dt){const pos=me.root.position,delta=me.velocity.clone().multiplyScalar(dt),radius=mechRadius(me);let next=pos.clone().add(delta);next.x=clamp(next.x,-CONFIG.arena/2,CONFIG.arena/2);next.z=clamp(next.z,-CONFIG.arena/2,CONFIG.arena/2);let blocked=hitsObstacle(next.x,next.z,radius),unitHit=mechCollisionAt(me,next.x,next.z);if(unitHit){const ox=unitHit.other.root.position.x,oz=unitHit.other.root.position.z,nx=(pos.x-ox)/(Math.hypot(pos.x-ox,pos.z-oz)||1),nz=(pos.z-oz)/(Math.hypot(pos.x-ox,pos.z-oz)||1),inward=Math.min(0,delta.x*nx+delta.z*nz),slideX=delta.x-nx*inward,slideZ=delta.z-nz*inward,candidate=pos.clone();candidate.x+=slideX;candidate.z+=slideZ;if(!hitsObstacle(candidate.x,candidate.z,radius)&&!mechCollisionAt(me,candidate.x,candidate.z))next=candidate;else next=pos.clone();blocked=true;me.blockedByUnit=unitHit.other.name}else me.blockedByUnit=null;if(blocked&&!unitHit){const slideX=pos.clone();slideX.x=next.x;const slideZ=pos.clone();slideZ.z=next.z;if(!hitsObstacle(slideX.x,slideX.z,radius)&&!mechCollisionAt(me,slideX.x,slideX.z))next=slideX;else if(!hitsObstacle(slideZ.x,slideZ.z,radius)&&!mechCollisionAt(me,slideZ.x,slideZ.z))next=slideZ;else next=pos.clone()}me.blocked=blocked&&me.velocity.length()>.1;me.blockedLatch=me.blocked?2.5:Math.max(0,(me.blockedLatch||0)-dt);me.root.position.copy(next);me.root.rotation.y=me.heading;const speed=me.velocity.length(),activity=Math.min(1,speed/4+Math.abs(me.turnRate||0)*.55);me.step+=(speed*.72+Math.abs(me.turnRate||0)*1.35)*dt;me.torso.position.y=4.45+Math.sin(me.step*2)*.11*activity;me.torso.rotation.y=me.torsoYaw;me.torso.rotation.z=Math.sin(me.step)*.035*activity;me.legRigs.forEach((leg,i)=>{const phase=me.step+(i?Math.PI:0);leg.rotation.x=Math.sin(phase)*.25*activity;leg.position.y=4.05-Math.max(0,Math.sin(phase))*.06*activity});me.weapons.forEach(w=>w.position.z+=(w.userData.baseZ-w.position.z)*Math.min(1,dt*16))}

function fire(me,target,index){if(!me.alive||me.cooldown[index]>0||me.ammo[index]<=0)return;const w=me.loadout[index];me.cooldown[index]=w.rate;me.weapons[index].position.z-=index ? .38 : .18;if(Number.isFinite(me.ammo[index]))me.ammo[index]--;me.heat=Math.min(100,me.heat+(index?18:4));const origin=new THREE.Vector3();me.weapons[index].getWorldPosition(origin);origin.y+=.1;const aim=target.root.position.clone().add(new THREE.Vector3(0,5.4,0));const direction=aim.sub(origin).normalize();const visual=index?new THREE.Mesh(new THREE.SphereGeometry(.18,7,7),new THREE.MeshBasicMaterial({color:0xff763b})):new THREE.Mesh(new THREE.SphereGeometry(.09,6,6),new THREE.MeshBasicMaterial({color:0xffe098}));visual.position.copy(origin);scene.add(visual);projectiles.push({mesh:visual,owner:me,target,velocity:direction.multiplyScalar(index?30:78),damage:w.damage,life:2,homing:index===1});const flash=new THREE.PointLight(index?0xff4e22:0xffd68a,25,7,1);flash.position.copy(origin);scene.add(flash);setTimeout(()=>scene.remove(flash),65)}
function updateProjectiles(dt){for(let i=projectiles.length-1;i>=0;i--){const p=projectiles[i];if(p.homing&&p.target.alive){const desired=p.target.root.position.clone().add(new THREE.Vector3(0,5,0)).sub(p.mesh.position).normalize().multiplyScalar(24);p.velocity.lerp(desired,dt*2.2)}p.mesh.position.addScaledVector(p.velocity,dt);p.life-=dt;if(p.mesh.position.distanceTo(p.target.root.position.clone().add(new THREE.Vector3(0,4.5,0)))<2.2){damage(p.target,p.damage,p.owner);scene.remove(p.mesh);projectiles.splice(i,1)}else if(p.life<=0){scene.remove(p.mesh);projectiles.splice(i,1)}}}
function powerDown(me){me.alive=false;me.shutdown=true;me.velocity.set(0,0,0);me.lastAction='OFFLINE';me.command=null;me.torso.position.y=4.32;me.torso.rotation.x=.06;me.root.traverse(node=>{if(!node.isMesh)return;const materials=Array.isArray(node.material)?node.material:[node.material];for(const material of materials){if(material.emissive){material.emissive.setHex(0x000000);material.emissiveIntensity=0}if(material.color)material.color.multiplyScalar(.28);material.roughness=Math.min(1,(material.roughness||.5)+.25)}});if(me===cameraMech){const teammate=(me.team==='BLUE'?activeBlue:activeRed).find(unit=>unit.alive&&unit!==me),any=[...activeBlue,...activeRed].find(unit=>unit.alive&&unit!==me);cameraMech=teammate||any||me}}
function damage(me,amount,attacker){me.health=Math.max(0,me.health-amount);shake=.35;if(attacker===player){$('#hit-marker').classList.add('show');setTimeout(()=>$('#hit-marker').classList.remove('show'),90)}if(me.health<=0&&me.alive){powerDown(me);const blueAlive=activeBlue.some(x=>x.alive),redAlive=activeRed.some(x=>x.alive);if(!redAlive)endMatch('VICTORY');else if(!blueAlive)endMatch('DEFEAT')}}

function chooseTarget(me,enemies){const alive=enemies.filter(x=>x.alive);if(!alive.length)return null;const visible=alive.filter(x=>canSee(me,x));return (visible.length?visible:alive).sort((a,b)=>me.root.position.distanceTo(a.root.position)-me.root.position.distanceTo(b.root.position))[0]}
function shareTeamContact(team,opponents){let sighting=null,spotter=null;for(const ally of team.filter(m=>m.alive)){const seen=opponents.filter(m=>m.alive&&canSee(ally,m)).sort((a,b)=>ally.root.position.distanceTo(a.root.position)-ally.root.position.distanceTo(b.root.position))[0];if(seen){sighting=seen;spotter=ally;break}}if(!sighting)return;const contact={event:'TEAM_CONTACT',targetId:sighting.name,reportedBy:spotter.name,position:{x:+sighting.root.position.x.toFixed(1),z:+sighting.root.position.z.toFixed(1)},health:+sighting.health.toFixed(0),at:+elapsed.toFixed(1)};for(const ally of team){ally.teamContact=contact;ally.navTarget={...contact.position,seenAt:elapsed}}}
function updatePlayer(dt){if(!player.alive)return;const target=player.currentTarget||chooseTarget(player,activeRed);if(!target)return;const manual=keys.KeyA||keys.KeyD||keys.KeyW||keys.KeyS||keys.KeyQ||keys.KeyE||keys.Space||keys.KeyR;if(!manual&&player.command){applyBot(player,target,player.command,dt);return}let turn=(keys.KeyA?-1:0)+(keys.KeyD?1:0),throttle=(keys.KeyW?1:0)+(keys.KeyS?-1:0);player.turnRate=turn;player.heading+=turn*dt*.95;player.torsoYaw=clamp(player.torsoYaw+((keys.KeyQ?-1:0)+(keys.KeyE?1:0))*dt*1.35,-1.65,1.65);player.velocity.set(Math.sin(player.heading)*throttle*6.5,0,Math.cos(player.heading)*throttle*6.5);moveMech(player,dt);if(keys.Space)fire(player,target,0);if(keys.KeyR){fire(player,target,1);keys.KeyR=false}player.lastAction=keys.Space?'FIRING':throttle?'MOVING':'TRACKING'}
function updateCamera(dt){const observed=cameraMech,viewHeading=observed.heading+observed.torsoYaw,forward=new THREE.Vector3(Math.sin(viewHeading),0,Math.cos(viewHeading)),focus=observed.root.position.clone().add(new THREE.Vector3(0,5.25*(observed.elite?1.12:1),0)),desired=focus.clone().addScaledVector(forward,-13).add(new THREE.Vector3(0,4.8,0));if(obstacles.some(o=>segmentHitsObstacle(focus,desired,o,.35))){for(let t=.15;t<=1;t+=.05){const probe=focus.clone().lerp(desired,t);if(hitsObstacle(probe.x,probe.z,.35)){desired.copy(focus.clone().lerp(desired,Math.max(.12,t-.08)));break}}}camera.position.lerp(desired,1-Math.pow(.001,dt));if(shake){camera.position.add(new THREE.Vector3((Math.random()-.5)*shake,(Math.random()-.5)*shake,(Math.random()-.5)*shake));shake=Math.max(0,shake-dt*2)}camera.lookAt(focus.clone().addScaledVector(forward,7))}

function logDecision(cmd,s){const row=document.createElement('div');row.className='log-item';const nav=cmd.navigation.forward>0?'FORWARD':cmd.navigation.forward<0?'BACK':cmd.navigation.turn<0?'LEGS L':cmd.navigation.turn>0?'LEGS R':'HOLD';const turret=cmd.torso.turn<0?'TURRET L':cmd.torso.turn>0?'TURRET R':'TURRET HOLD',safety=cmd.navigation.safetyOverride?' <b>⚠ OVERRIDE</b>':'';row.innerHTML=`<time>${s.at.toFixed(1)}s</time><span><b>${cmd.targeting.track.toUpperCase()}</b> · ${nav} · ${turret} · ${cmd.weapon.secondary?'VLR-4':cmd.weapon.primary?'AC-12':'SAFE'}${safety}</span>`;$('#decision-log').prepend(row);while($('#decision-log').children.length>5)$('#decision-log').lastChild.remove()}
function logBroadcast(event){const row=document.createElement('div');row.className='log-item';row.innerHTML=`<time>${event.at.toFixed(1)}s</time><span><b>CONTACT!</b> ${event.targetId} → ALL CONTROLLERS</span>`;$('#decision-log').prepend(row)}
function updateHud(){const target=player.currentTarget||chooseTarget(player,activeRed),visible=target&&canSee(player,target)&&target.alive;$('#target-card').classList.toggle('visible',!!visible);if(visible){$('#target-name').textContent=target.name;$('#target-distance').textContent=`${player.root.position.distanceTo(target.root.position).toFixed(0)} M`;$('#target-action').textContent=target.lastAction}$('#player-health').style.width=`${player.health}%`;$('#player-health-text').textContent=Math.ceil(player.health);$('#heat').textContent=`${Math.round(player.heat)}°C`;$('#ammo-1').textContent=player.ammo[1];$('#memory-count').textContent=`${player.memory.length}/${CONFIG.memorySize}`;const timeline=$('#memory-timeline');timeline.replaceChildren(...player.memory.map(m=>{const e=document.createElement('i');e.className='memory-tick'+(m.enemy?' contact':'');e.style.height=`${12+(m.enemy?m.enemy.health*.42:8)}px`;return e}));if(target){const rel=target.root.position.clone().sub(player.root.position),scale=46/CONFIG.sightRange;$('#radar-enemy').style.left=`${50+clamp(rel.x*scale,-45,45)}px`;$('#radar-enemy').style.top=`${50+clamp(rel.z*scale,-45,45)}px`}$('#radar-enemy').style.display=visible?'block':'none'}
function endMatch(result){running=false;$('#status').textContent=result;$('#status').style.color=result==='VICTORY'?'var(--blue)':'var(--red)'}

let last=performance.now(),frames=0,fpsTime=0;
function loop(now){requestAnimationFrame(loop);const dt=Math.min((now-last)/1000,.04);last=now;if(running){elapsed+=dt;timeLeft=Math.max(0,timeLeft-dt);const active=[...activeBlue,...activeRed];if(gameMode==='squad'){shareTeamContact(activeBlue,activeRed);shareTeamContact(activeRed,activeBlue)}for(const m of active){m.cooldown=m.cooldown.map(v=>Math.max(0,v-dt));m.heat=Math.max(0,m.heat-dt*7);if(!m.alive)continue;const opponents=m.team==='BLUE'?activeRed:activeBlue,target=chooseTarget(m,opponents);m.currentTarget=target;if(m!==enemy||gameMode!=='training'){m.nextDecision=(m.nextDecision??elapsed+Math.random()*1.2);if(target&&elapsed>=m.nextDecision){requestJev(m,target);m.nextDecision=elapsed+1.25}}}updatePlayer(dt);for(const m of active){if(m===player||!m.alive)continue;if(gameMode==='training'&&m===enemy){m.lastAction='STATIC TARGET';m.velocity.set(0,0,0);continue}if(m.command&&m.currentTarget)applyBot(m,m.currentTarget,m.command,dt)}for(const m of active)if(m.alive&&(gameMode!=='training'||m===player))emitSmoke(m,dt);updateSmoke(dt);updateProjectiles(dt);updateHud();if(timeLeft<=0){const blueHp=activeBlue.reduce((n,m)=>n+m.health,0),redHp=activeRed.reduce((n,m)=>n+m.health,0);endMatch(blueHp>=redHp?'VICTORY':'DEFEAT')}$('#match-time').textContent=`${String(Math.floor(timeLeft/60)).padStart(2,'0')}:${String(Math.floor(timeLeft%60)).padStart(2,'0')}`}updateCamera(dt);renderer.render(scene,camera);frames++;fpsTime+=dt;if(fpsTime>1){$('#fps').textContent=Math.round(frames/fpsTime);frames=0;fpsTime=0}}
requestAnimationFrame(loop);

$('#launch').addEventListener('click',()=>{allMechs.forEach(m=>m.root.visible=false);if(gameMode==='squad'){activeBlue=blueTeam;activeRed=redTeam}else{activeBlue=[player];activeRed=[enemy]}[...activeBlue,...activeRed].forEach(m=>m.root.visible=true);cameraMech=player;running=true;if(gameMode==='training'){enemy.name='TARGET OBSTACLE';$('#target-name').textContent='TARGET OBSTACLE';enemy.legs.visible=false;enemy.torso.visible=false;targetObstacle.visible=true;directive='Найди и уничтожь неподвижное укреплённое препятствие.'}$('#start-screen').classList.add('hidden');player.currentTarget=chooseTarget(player,activeRed);if(player.currentTarget)requestJev(player,player.currentTarget)});
document.querySelectorAll('.mode button').forEach(b=>b.addEventListener('click',()=>{gameMode=b.dataset.mode;document.querySelectorAll('.mode button').forEach(x=>x.classList.toggle('active',x===b))}));
$('.strategy-tabs').addEventListener('click',e=>{if(!e.target.dataset.strategy)return;strategy=e.target.dataset.strategy;document.querySelectorAll('.strategy-tabs button').forEach(b=>b.classList.toggle('active',b===e.target))});
$('#apply-directive').addEventListener('click',()=>{directive=$('#directive').value.trim();const b=$('#apply-directive');b.firstChild.textContent='DIRECTIVE APPLIED ';setTimeout(()=>b.firstChild.textContent='EXECUTE DIRECTIVE ',900)});
document.querySelectorAll('.loadout button').forEach((b,i)=>b.addEventListener('click',()=>{document.querySelectorAll('.loadout button').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(i===1)fire(player,enemy,1)}));
$('#exit-button').addEventListener('click',()=>location.reload());
$('#debug-button').addEventListener('click',()=>window.open('/api/logs','_blank'));
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
updateCamera(.016);updateHud();
